import {gettext} from 'core/utils';

export const getTimezoneLabel = (tz) => {
    const labels = getTimezoneLabels();

    return labels[tz];
};

const getTimezoneLabels = () => ({
    'Africa/Abidjan': gettext('Africa/Abidjan'),
    'Africa/Accra': gettext('Africa/Accra'),
    'Africa/Cairo': gettext('Africa/Cairo'),
    'Africa/Casablanca': gettext('Africa/Casablanca'),
    'Africa/Dakar': gettext('Africa/Dakar'),
    'Africa/Johannesburg': gettext('Africa/Johannesburg'),
    'Africa/Khartoum': gettext('Africa/Khartoum'),
    'Africa/Kinshasa': gettext('Africa/Kinshasa'),
    'Africa/Lagos': gettext('Africa/Lagos'),
    'Africa/Nairobi': gettext('Africa/Nairobi'),
    'Africa/Tunis': gettext('Africa/Tunis'),
    'America/Anchorage': gettext('America/Anchorage'),
    'America/Argentina/Buenos_Aires': gettext('America/Argentina/Buenos Aires'),
    'America/Bogota': gettext('America/Bogota'),
    'America/Caracas': gettext('America/Caracas'),
    'America/Chicago': gettext('America/Chicago'),
    'America/Guatemala': gettext('America/Guatemala'),
    'America/Halifax': gettext('America/Halifax'),
    'America/Havana': gettext('America/Havana'),
    'America/La_Paz': gettext('America/La Paz'),
    'America/Lima': gettext('America/Lima'),
    'America/Los_Angeles': gettext('America/Los Angeles'),
    'America/Manaus': gettext('America/Manaus'),
    'America/Mexico_City': gettext('America/Mexico City'),
    'America/Montevideo': gettext('America/Montevideo'),
    'America/New_York': gettext('America/New York'),
    'America/Phoenix': gettext('America/Phoenix'),
    'America/Santiago': gettext('America/Santiago'),
    'America/Sao_Paulo': gettext('America/Sao Paulo'),
    'America/Tegucigalpa': gettext('America/Tegucigalpa'),
    'America/Tijuana': gettext('America/Tijuana'),
    'America/Toronto': gettext('America/Toronto'),
    'America/Vancouver': gettext('America/Vancouver'),
    'America/Winnipeg': gettext('America/Winnipeg'),
    'Asia/Almaty': gettext('Asia/Almaty'),
    'Asia/Baghdad': gettext('Asia/Baghdad'),
    'Asia/Baku': gettext('Asia/Baku'),
    'Asia/Bangkok': gettext('Asia/Bangkok'),
    'Asia/Beirut': gettext('Asia/Beirut'),
    'Asia/Colombo': gettext('Asia/Colombo'),
    'Asia/Dhaka': gettext('Asia/Dhaka'),
    'Asia/Dili': gettext('Asia/Dili'),
    'Asia/Dubai': gettext('Asia/Dubai'),
    'Asia/Irkutsk': gettext('Asia/Irkutsk'),
    'Asia/Jakarta': gettext('Asia/Jakarta'),
    'Asia/Jerusalem': gettext('Asia/Jerusalem'),
    'Asia/Kabul': gettext('Asia/Kabul'),
    'Asia/Karachi': gettext('Asia/Karachi'),
    'Asia/Kathmandu': gettext('Asia/Kathmandu'),
    'Asia/Krasnoyarsk': gettext('Asia/Krasnoyarsk'),
    'Asia/Kuala_Lumpur': gettext('Asia/Kuala Lumpur'),
    'Asia/Manila': gettext('Asia/Manila'),
    'Asia/Novosibirsk': gettext('Asia/Novosibirsk'),
    'Asia/Pyongyang': gettext('Asia/Pyongyang'),
    'Asia/Rangoon': gettext('Asia/Rangoon'),
    'Asia/Riyadh': gettext('Asia/Riyadh'),
    'Asia/Seoul': gettext('Asia/Seoul'),
    'Asia/Singapore': gettext('Asia/Singapore'),
    'Asia/Tashkent': gettext('Asia/Tashkent'),
    'Asia/Tehran': gettext('Asia/Tehran'),
    'Asia/Tokyo': gettext('Asia/Tokyo'),
    'Asia/Vladivostok': gettext('Asia/Vladivostok'),
    'Asia/Yakutsk': gettext('Asia/Yakutsk'),
    'Asia/Yekaterinburg': gettext('Asia/Yekaterinburg'),
    'Australia/Adelaide': gettext('Australia/Adelaide'),
    'Australia/Melbourne': gettext('Australia/Melbourne'),
    'Australia/Perth': gettext('Australia/Perth'),
    'Australia/Sydney': gettext('Australia/Sydney'),
    'Europe/Athens': gettext('Europe/Athens'),
    'Europe/Belgrade': gettext('Europe/Belgrade'),
    'Europe/Berlin': gettext('Europe/Berlin'),
    'Europe/Brussels': gettext('Europe/Brussels'),
    'Europe/Bucharest': gettext('Europe/Bucharest'),
    'Europe/Dublin': gettext('Europe/Dublin'),
    'Europe/Helsinki': gettext('Europe/Helsinki'),
    'Europe/Istanbul': gettext('Europe/Istanbul'),
    'Europe/Kiev': gettext('Europe/Kiev'),
    'Europe/Lisbon': gettext('Europe/Lisbon'),
    'Europe/London': gettext('Europe/London'),
    'Europe/Madrid': gettext('Europe/Madrid'),
    'Europe/Minsk': gettext('Europe/Minsk'),
    'Europe/Moscow': gettext('Europe/Moscow'),
    'Europe/Paris': gettext('Europe/Paris'),
    'Europe/Prague': gettext('Europe/Prague'),
    'Europe/Rome': gettext('Europe/Rome'),
    'Europe/Sofia': gettext('Europe/Sofia'),
    'Europe/Stockholm': gettext('Europe/Stockholm'),
    'Pacific/Auckland': gettext('Pacific/Auckland'),
    'Pacific/Honolulu': gettext('Pacific/Honolulu'),
    'Pacific/Noumea': gettext('Pacific/Noumea'),
    'Pacific/Port_Moresby': gettext('Pacific/Port Moresby'),
});
