name: 'Setup E2E Environment'
description: 'Install e2e runtime dependencies and start services'

runs:
  using: "composite"
  steps:
    - run: npm ci
      working-directory: ./
      shell: bash

    - run: npm ci
      working-directory: ./build-tools
      shell: bash

    - run: npm ci
      working-directory: ./e2e/client
      shell: bash

    - run: npm run start-client-server
      working-directory: ./e2e/client
      shell: bash

    - name: Start superdesk server
      run: docker compose up -d --no-build
      working-directory: e2e/server
      shell: bash
