import 'bootstrap.less'; // styles
import 'vendor';
import 'core';
import 'templates-cache.generated'; // generated by grunt 'ngtemplates' task
import 'apps';

/* globals __SUPERDESK_CONFIG__: true */
const appConfig = __SUPERDESK_CONFIG__;

if (appConfig.features.useTansaProofing) {
    require('apps/tansa');
}

// non-mock app configuration must live here to allow tests to override
// since tests do not import this file.
angular.module('superdesk.config').constant('config', appConfig);

let body = angular.element('body');
body.ready(function() {
    angular.bootstrap(body, [
        'superdesk.config',
        'superdesk.core',
        'superdesk.apps'
    ], {strictDi: true});

    window.superdeskIsReady = true;
});
