// styles
import './comments/comments.less';
import './metadata/metadata.less';
import './packages/packages.less';
import './styles/authoring.less';
import './styles/multiedit.less';
import './styles/themes.less';
import './styles/unused.less';
import './versioning/history/history.less';
import './versioning/versions/versions.less';
import './widgets/widgets-article.less';

// scripts
import './authoring';
import './widgets/widgets';
import './comments/comments';
import './versioning/versioning';
import './versioning/versions/versions';
import './versioning/history/history';
import './metadata/metadata';
import './workqueue/workqueue';
import './packages/packages';
import './editor/find-replace';
import './multiedit/multiedit';
import './macros/macros';
