// styles
import './comments/comments.scss';
import './track-changes/styles.scss';
import './metadata/metadata.scss';
import './packages/packages.scss';
import './styles/authoring.scss';
import './styles/multiedit.scss';
import './styles/themes.scss';
import './versioning/history/history.scss';
import './versioning/versions/versions.scss';
import './widgets/widgets-article.scss';

// scripts
import './authoring';
import './widgets/widgets';
import './comments/comments';
import './track-changes/inline-comments';
import './track-changes/suggestions';
import './attachments/attachments';
import './versioning/versioning';
import './versioning/versions/versions';
import './versioning/history/history';
import './metadata/metadata';
import './translations/index';
import './workqueue/workqueue';
import './packages/packages';
import './editor/find-replace';
import './multiedit/multiedit';
import './compare-versions/index';
import './macros/macros';
