
DEBUG = False
SUPERDESK_TESTING = True

SERVER_NAME = 'localhost:5000'
URL_PROTOCOL = 'http'
URL_PREFIX = 'api'

CLIENT_URL = 'http://localhost:9000'

MONGO_DBNAME = 'superdesk_e2e'
ARCHIVED_DBNAME = 'superdesk_e2e_archived'
LEGAL_ARCHIVE_DBNAME = 'superdesk_e2e_legal_archive'
CONTENTAPI_MONGO_DBNAME = 'contentapi_e2e'

ELASTICSEARCH_INDEX = MONGO_DBNAME
CONTENTAPI_ELASTICSEARCH_INDEX = CONTENTAPI_MONGO_DBNAME

LEGAL_ARCHIVE = True
CELERY_TASK_ALWAYS_EAGER = True
